<?php

use Dvsa\Mot\Frontend\GoogleAnalyticsModule\Package;

?>
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title><?php echo Package::NAME . ' - ' .  Package::DESCRIPTION; ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
</html>
